# -*- coding: utf-8 -*-
"""Amazon Order Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ccHLfhb6XONcbzusBTjjoQRhkWc-WBnB
"""

import pandas as pd

amz_data = pd.read_csv('/content/amazon_order_history - amazon_order_history.csv')

amz_data

amz_data.shape

amz_data.isnull().sum()

amz_data['date'] = pd.to_datetime(amz_data['date'])

amz_data.head()

amz_data['date'].dtype

amz_data['total'].dtype

amz_data['total'] = pd.to_numeric(amz_data['total'])

amz_data.plot.bar(x = 'date' , y = 'total' , figsize = (10, 8))

daily_orders = amz_data.groupby('date').sum()[ 'total']
daily_orders

daily_orders.plot.bar(figsize=(10,8))

amz_data.head()

amz_data['date'] = pd.to_datetime(amz_data['date'])
amz_data['month'] = amz_data['date'].dt.month

amz_data.head()

monthly_orders = amz_data.groupby ('month').sum()['total']
monthly_orders